name: CI-CD Pipeline
on:
  push:
    branches: ["main"]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v3
    
    - name: JDK setup
      uses: actions/setup-java@3
      with:
        java-version: '17'
    
    - name: Build
    - run: ./gradlew bootJar

    - name: Docker login
    - run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build Docker image
    - run: docker build -t ${{ secrets.DOCKER_USERNAME }}/prep-app:latest .

    - name: Push Docker image
    - run: docker push ${{ secrets.DOCKER_USERNAME }}/prep-app:latest
